feeds_extra:
  - https://www.prnewswire.com/rss/latin-america-latest-news.rss
  - https://www.businesswire.com/portal/site/home/news/subject?rss=1&vnsId=11390
  - https://www.startupeable.com/feed/
  - https://startups.lat/feed/
  - https://medium.com/feed/500-startups-latam
  - https://www.seedstars.com/feed/
  - https://endeavor.org/feed/
  - https://blog.platan.us/feed/
  - https://www.startupchile.org/feed/
  - https://blog.parallel18.com/feed/
