name: VC Sourcing (Daily)

on:
  schedule:
    - cron: "30 14 * * *"     # ~08:30 America/Costa_Rica (UTC-based)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service account JSON
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${{ secrets.GCP_SA_JSON }}" ]; then
          printf '%s' "${{ secrets.GCP_SA_JSON }}" > service_account.json
            echo "Wrote service_account.json from GCP_SA_JSON"
          elif [ -n "${{ secrets.GCP_SA_JSON_BASE64 }}" ]; then
            printf '%s' "${{ secrets.GCP_SA_JSON_BASE64 }}" | base64 -d > service_account.json
            echo "Wrote service_account.json from GCP_SA_JSON_BASE64"
          else
            echo "❌ Missing secret: add GCP_SA_JSON (raw JSON) or GCP_SA_JSON_BASE64 (base64-encoded)."
           exit 1
            fi

          # Sanity-check the JSON so we fail fast with a clear error
          python - <<'PY'
            import json, sys
          json.load(open('service_account.json'))
          print("service_account.json OK")
          PY


          - name: Execute notebook with parameters
            run: |
            papermill "VC_Sourcing_Agent_Colab (3).ipynb" executed.ipynb \
            -p GOOGLE_SHEET_ID "${{ secrets.GOOGLE_SHEET_ID }}" \
            -p TZ "${{ secrets.TZ }}"


      - name: Upload executed notebook (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_number }}
          path: executed.ipynb
