name: VC Sourcing (Daily)

on:
  schedule:
    - cron: "30 14 * * *"     # ~08:30 America/Costa_Rica (UTC-based)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service account JSON
        shell: bash
        run: |
          printf '%s' "${{ secrets.GCP_SA_JSON }}" > service_account.json
          python - << 'PY'
          import json, sys
          json.load(open('service_account.json'))  # validate JSON
          print("service_account.json OK")
          PY

      - name: Execute notebook with parameters
        run: |
          papermill vc_sourcing_agent.ipynb executed.ipynb \
            -p GOOGLE_SHEET_ID "${{ secrets.GOOGLE_SHEET_ID }}" \
            -p TZ "${{ secrets.TZ }}"

      - name: Upload executed notebook (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_number }}
          path: executed.ipynb
